CommunityPlantsWebAppASpMVC/CommunityPlantsWebAppASpMVC/Controllers/KaufsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GemeinschaftsBalkonWebApp01.Models;
using PagedList;

namespace GemeinschaftsBalkonWebApp01.Controllers
{
    [Authorize]
    public class KaufsController : Controller
    {
        private PflanzEntities db = new PflanzEntities();

        //GET: Kaufs
        public ActionResult Index(string q)
        {
            ViewBag.suchstring = q;
            var kaufs = db.Kaufs.Include(s => s.User);

            if (q != null) kaufs = kaufs.Where(s => s.K_Shop.Contains(q));

            return View(kaufs.ToList());
        }

        //GET: /Schueler/   aber mit Ajaxcall
        //     damit der Ajaxcall clientseitig funktioniert muss Package Micsosoft jquery unobtrusive ajax eingebunden werden
        //      am Ende des indes.cshtml  ist das script auch eingebunden !!!

        public ActionResult ShopSearch(string q)
        {
            ViewBag.suchstring = q;

            var kaufs = db.Kaufs.Include(k => k.User);

            if (q != null) kaufs = kaufs.Where(s => s.K_Shop.Contains(q));

            return PartialView("_kauflist", kaufs.ToList());
        }




        // GET: Kaufs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null) //|| id != (int)Session["uid"])    //um nicht als andrerer user über url daten zu ändern
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kauf kauf = db.Kaufs.Find(id);
            if (kauf == null)
            {
                return HttpNotFound();
            }
            return View(kauf);
        }

        // GET: Kaufs/Create
        public ActionResult Create()
        {

            int uid = (int)Session["uid"];                                //int?
            var erg = from u in db.Users where u.U_ID == uid select u;
            if (erg.Count() <= 0)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            ViewBag.K_U_ID = new SelectList(db.Users, "U_ID", "U_Name");
            return View();
        }

        // POST: Kaufs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "K_ID,K_Shop,K_Datum,K_Preis,K_U_ID")] Kauf kauf)
        {
            if (ModelState.IsValid)
            {
                db.Kaufs.Add(kauf);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.K_U_ID = new SelectList(db.Users, "U_ID", "U_Name", kauf.K_U_ID);
            return View(kauf);
        }

        // GET: Kaufs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kauf kauf = db.Kaufs.Find(id);
            if (kauf == null)
            {
                return HttpNotFound();
            }
            ViewBag.K_U_ID = new SelectList(db.Users, "U_ID", "U_Name", kauf.K_U_ID);
            return View(kauf);
        }

        // POST: Kaufs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "K_ID,K_Shop,K_Datum,K_Preis,K_U_ID")] Kauf kauf)
        {
            //// zu Prüfzwecken wird der Schüler mit S_Schnr aus der db gelesen
            //Kauf kaufc1 = db.Kaufs.Find(kauf.K_ID);

            //if (kaufc1.User.U_ID != (int)Session["uid"])
            //    ModelState.AddModelError("", "Rechnung NUR vom Käufer editierbar");

            if (ModelState.IsValid)
            {
                db.Entry(kauf).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.K_U_ID = new SelectList(db.Users, "U_ID", "U_Name", kauf.K_U_ID);
            return View(kauf);
        }

        // GET: Kaufs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Kauf kauf = db.Kaufs.Find(id);
            if (kauf == null || kauf.User.U_ID != (int)Session["uid"])

            if (kauf == null)
            {
                return HttpNotFound();
            }
            return View(kauf);
        }

        // POST: Kaufs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kauf kauf = db.Kaufs.Find(id);
            if (kauf.User.U_ID != (int)Session["uid"])
            return HttpNotFound();

            db.Kaufs.Remove(kauf);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CommunityPlantsWebAppASpMVC/CommunityPlantsWebAppASpMVC/Controllers/TopfsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GemeinschaftsBalkonWebApp01.Models;

namespace GemeinschaftsBalkonWebApp01.Controllers
{
    [Authorize]
    public class TopfsController : Controller
    {
        private PflanzEntities db = new PflanzEntities();

        // GET: Topfs
        public ActionResult Index()
        {
            var topfs = db.Topfs.Include(t => t.Standort);
            return View(topfs.ToList());
        }

        // GET: Topfs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topf topf = db.Topfs.Find(id);
            if (topf == null)
            {
                return HttpNotFound();
            }
            return View(topf);
        }

        // GET: Topfs/Create
        public ActionResult Create()
        {
            ViewBag.T_Standort = new SelectList(db.Standorts, "SO_ID", "SO_Bez");
            return View();
        }

        // POST: Topfs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "T_Bez,T_Breite,T_Tiefe,T_Hoehe,T_Standort,T_ID")] Topf topf)
        {
            if (ModelState.IsValid)
            {
                db.Topfs.Add(topf);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.T_Standort = new SelectList(db.Standorts, "SO_ID", "SO_Bez", topf.T_Standort);
            return View(topf);
        }

        // GET: Topfs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topf topf = db.Topfs.Find(id);
            if (topf == null)
            {
                return HttpNotFound();
            }
            ViewBag.T_Standort = new SelectList(db.Standorts, "SO_ID", "SO_Bez", topf.T_Standort);
            return View(topf);
        }

        // POST: Topfs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "T_Bez,T_Breite,T_Tiefe,T_Hoehe,T_Standort,T_ID")] Topf topf)
        {
            if (ModelState.IsValid)
            {
                db.Entry(topf).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.T_Standort = new SelectList(db.Standorts, "SO_ID", "SO_Bez", topf.T_Standort);
            return View(topf);
        }

        // GET: Topfs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topf topf = db.Topfs.Find(id);
            if (topf == null)
            {
                return HttpNotFound();
            }
            return View(topf);
        }

        // POST: Topfs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Topf topf = db.Topfs.Find(id);
            db.Topfs.Remove(topf);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CommunityPlantsWebAppASpMVC/CommunityPlantsWebAppASpMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @*derTitel der im Browser-Reiter angezeigt wird*@
    <title>@ViewBag.Title - CommunityPLANTS</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!--navbar-inverse schwarzer hintergrund weiße schrift-->
    <div class="navbar navbar-inverse navbar-fixed-top justify-content-center">
        <a class="navbar-brand" href="#">
            <img src="~/pngwing.com.png" alt="Logo" style="width:30px ">
        </a>
        <div class="container">

            <!--Burger-->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CommunityPLANTS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <!--Header-->
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("News", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    @*<li>@Html.ActionLink("Pflanzen", "Index", "Pflanzens")</li>
            <li>@Html.ActionLink("Blumentöpfe", "Index", "Topfs")</li>
            <li>@Html.ActionLink("Freiflächen", "Index", "Standorts")</li>
            <li>@Html.ActionLink("Schädlinge", "Index", "Schaedlings")</li>
            <li>@Html.ActionLink("Käufe", "Index", "Kaufs")</li>
            <li>@Html.ActionLink("Paten", "Index", "Users")</li>*@
                    <!--hier kann man weitere Menüpunkte einfügen-->
                    
                </ul>
                @Html.Partial("_LoginPartial")
                @*
        <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Link 1</a>
            <a class="dropdown-item" href="#">Link 2</a>
            <a class="dropdown-item-text" href="#">Text Link</a>
            <span class="dropdown-item-text">Just Text</span>
        </div>
                *@
                @*@Html.Partial("_LoginPartial")*@

            </div>
        </div>
    </div>

    <div class="container body-content">

        @RenderBody()
        <!--an diesr stelle fügt sich der gewählte view ein-->

        <hr />
        <footer>
            <a class="navbar-brand" href="#">
                <img src="~/pngwing.com.png" alt="Logo" style="width:30px ">
            </a>

            <div class="navbar-inverse navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    <li>@Html.ActionLink("News", "About", "Home")</li>
                    

                </ul>

                @*<form class="navbar-form navbar-right" action="/action_page.php">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search" name="search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>*@

            </div>

            <p>&copy; @DateTime.Now.Year - SCH11202</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <!--hier könnte noch ein zusätzliches JavaScript eingebaut werden-->
</body>
</html>