CommunityPlantsWebAppASpMVC/CommunityPlantsWebAppASpMVC/Models/Pflanzen.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityPlantsWebAppASpMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pflanzen
    {
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public Nullable<System.DateTime> P_Gepflanzt { get; set; }
        public Nullable<int> P_Kauf { get; set; }
        public Nullable<int> P_Topf { get; set; }
        public Nullable<int> P_Standort { get; set; }
        public Nullable<int> P_Steckbrief { get; set; }
        public Nullable<System.DateTime> P_Bluet_Von { get; set; }
        public Nullable<System.DateTime> P_Bluet_Bis { get; set; }
        public string P_Notiz { get; set; }
        public Nullable<int> P_Schaedling { get; set; }
        public Nullable<int> P_U_Besitzer { get; set; }
    
        public virtual Kauf Kauf { get; set; }
        public virtual Schaedling Schaedling { get; set; }
        public virtual Standort Standort { get; set; }
        public virtual Steckbrief Steckbrief { get; set; }
        public virtual Topf Topf { get; set; }
        public virtual User User { get; set; }
    }
}

CommunityPlantsWebAppASpMVC/CommunityPlantsWebAppASpMVC/Controllers/PflanzensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GemeinschaftsBalkonWebApp01.Models;

namespace GemeinschaftsBalkonWebApp01.Controllers
{
    [Authorize]
    public class PflanzensController : Controller
    {
        private PflanzEntities db = new PflanzEntities();


        
        // GET: Pflanzens/
        public ActionResult Index(int? ortsuche, int? suchuser) //rechte maus auf index Go to view
        {
            int uid = (int)Session["uid"];

            var pflanzens = db.Pflanzens.Include(p => p.Kauf).Include(p => p.Schaedling).Include(p => p.Standort).Include(p => p.Steckbrief).Include(p => p.Topf).Include(p => p.User);
            
            if (ortsuche != null)
            { 
                pflanzens = pflanzens.Where(op => op.P_Standort == ortsuche);
                ViewBag.ortsuche = "Pflanzen am " + ortsuche;                       //VB = um filteransicht einbauen zu können neben h2 Index @ViewBag.ortsuche einbauen für verwendung
                
            }

            if (suchuser != null)
            {
                pflanzens = pflanzens.Where(p => p.P_U_Besitzer == suchuser);
            }

            ViewBag.suchuser = new SelectList(db.Users, "U_ID", "U_Name");

            return View(pflanzens.ToList());
        }



        // GET: Pflanzens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)              
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pflanzen pflanzen = db.Pflanzens.Find(id);

            if (pflanzen == null)
            {
                return HttpNotFound();
            }
            return View(pflanzen);
/*
* Wenn 2PKs wären:
        public ActionResult Details(string klasse, string stunde)
                {
                    if (klasse == null || stunde == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    stunden stunden = db.stundens.Find(klasse, stunde); 

            bei Edit, delete und delete/5 (=delete conform 2.X weil dabei nachgefragt wird ob wirklich gelöscht werden soll)
 */
        }

        // GET: Pflanzens/Create
        public ActionResult Create()
        {
            int uid = (int)Session["uid"];

            var shopper = from u in db.Users where u.U_ID == uid select u;

            ViewBag.P_Kauf = new SelectList(db.Kaufs, "K_ID", "K_Shop");    
            ViewBag.P_Schaedling = new SelectList(db.Schaedlings, "S_ID", "S_Bez");
            ViewBag.P_Standort = new SelectList(db.Standorts, "SO_ID", "SO_Bez");
            ViewBag.P_Steckbrief = new SelectList(db.Steckbriefs, "ST_ID", "ST_Name");
            ViewBag.P_Topf = new SelectList(db.Topfs, "T_ID", "T_Bez");
            ViewBag.P_U_Besitzer = new SelectList(shopper, "U_ID", "U_Name");
            //} Session["lastschnr"] = schueler.S_SCHNR;
            return View();
            //hier kommt Token raus der nur von Post geöffnet werden kann hier generiert (next method überprüft) > kostet performance
        }

        // POST: Pflanzens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]      //submittbutton immer posts
        [ValidateAntiForgeryToken]      //schützt vor angriffen HttpRequests
        public ActionResult Create([Bind(Include = "P_ID,P_Name,P_Gepflanzt,P_Kauf,P_Topf,P_Standort,P_Steckbrief,P_Bluet_Von,P_Bluet_Bis,P_Notiz,P_Schaedling,P_U_Besitzer")] Pflanzen pflanzen)
        {
            if (ModelState.IsValid)
            {
                db.Pflanzens.Add(pflanzen);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.P_Kauf = new SelectList(db.Kaufs, "K_ID", "K_Shop", pflanzen.P_Kauf);
            ViewBag.P_Schaedling = new SelectList(db.Schaedlings, "S_ID", "S_Bez", pflanzen.P_Schaedling);
            ViewBag.P_Standort = new SelectList(db.Standorts, "SO_ID", "SO_Bez", pflanzen.P_Standort);
            ViewBag.P_Steckbrief = new SelectList(db.Steckbriefs, "ST_ID", "ST_Name", pflanzen.P_Steckbrief);
            ViewBag.P_Topf = new SelectList(db.Topfs, "T_ID", "T_Bez", pflanzen.P_Topf);
            ViewBag.P_U_Besitzer = new SelectList(db.Users, "U_ID", "U_Name", pflanzen.P_U_Besitzer);
            return View(pflanzen);
        }

        // GET: Pflanzens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pflanzen pflanzen = db.Pflanzens.Find(id);
            if (pflanzen == null)
            {
                return HttpNotFound();
            }
            ViewBag.P_Kauf = new SelectList(db.Kaufs, "K_ID", "K_Shop", pflanzen.P_Kauf);
            ViewBag.P_Schaedling = new SelectList(db.Schaedlings, "S_ID", "S_Bez", pflanzen.P_Schaedling);
            ViewBag.P_Standort = new SelectList(db.Standorts, "SO_ID", "SO_Bez", pflanzen.P_Standort);
            ViewBag.P_Steckbrief = new SelectList(db.Steckbriefs, "ST_ID", "ST_Name", pflanzen.P_Steckbrief);
            ViewBag.P_Topf = new SelectList(db.Topfs, "T_ID", "T_Bez", pflanzen.P_Topf);
            ViewBag.P_U_Besitzer = new SelectList(db.Users, "U_ID", "U_Name", pflanzen.P_U_Besitzer);
            return View(pflanzen);
        }

        // POST: Pflanzens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "P_ID,P_Name,P_Gepflanzt,P_Kauf,P_Topf,P_Standort,P_Steckbrief,P_Bluet_Von,P_Bluet_Bis,P_Notiz,P_Schaedling,P_U_Besitzer")] Pflanzen pflanzen)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pflanzen).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.P_Kauf = new SelectList(db.Kaufs, "K_ID", "K_Shop", pflanzen.P_Kauf);
            ViewBag.P_Schaedling = new SelectList(db.Schaedlings, "S_ID", "S_Bez", pflanzen.P_Schaedling);
            ViewBag.P_Standort = new SelectList(db.Standorts, "SO_ID", "SO_Bez", pflanzen.P_Standort);
            ViewBag.P_Steckbrief = new SelectList(db.Steckbriefs, "ST_ID", "ST_Name", pflanzen.P_Steckbrief);
            ViewBag.P_Topf = new SelectList(db.Topfs, "T_ID", "T_Bez", pflanzen.P_Topf);
            ViewBag.P_U_Besitzer = new SelectList(db.Users, "U_ID", "U_Name", pflanzen.P_U_Besitzer);
            return View(pflanzen);
        }

        // GET: Pflanzens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pflanzen pflanzen = db.Pflanzens.Find(id);
            if (pflanzen == null)
            {
                return HttpNotFound();
            }
            return View(pflanzen);
        }

        // POST: Pflanzens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pflanzen pflanzen = db.Pflanzens.Find(id);
            db.Pflanzens.Remove(pflanzen);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CommunityPlantsWebAppASpMVC/CommunityPlantsWebAppASpMVC/Views/Pflanzens/Create.cshtml
@model GemeinschaftsBalkonWebApp01.Models.Pflanzen

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Pflanzen</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.P_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.P_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.P_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.P_Gepflanzt, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.P_Gepflanzt, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.P_Gepflanzt, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.P_Kauf, null, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("P_Kauf", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.P_Kauf, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.P_Topf, null, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("P_Topf", null, "kein Blumentopf", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.P_Topf, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.P_Standort, null, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("P_Standort", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.P_Standort, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.P_Steckbrief, null, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("P_Steckbrief", null, "kein Steckbrief", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.P_Steckbrief, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.P_Bluet_Von, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.P_Bluet_Von, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.P_Bluet_Von, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.P_Bluet_Bis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.P_Bluet_Bis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.P_Bluet_Bis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.P_Notiz, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.P_Notiz, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.P_Notiz, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.P_Schaedling, null, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("P_Schaedling", null, "kein Schädling", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.P_Schaedling, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.P_U_Besitzer, null, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("P_U_Besitzer", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.P_U_Besitzer, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CommunityPlantsWebAppASpMVC/CommunityPlantsWebAppASpMVC/Views/Pflanzens/Delete.cshtml
@model GemeinschaftsBalkonWebApp01.Models.Pflanzen

@{
    ViewBag.Title = "Delete";
}

<h2>Löschen</h2>

<h3>Sind Sie sich sicher, dass Sie das Objekt löschen wollen?</h3>
<br />
<div>
    <h4>Diese Pflanze ist also eingegangen:</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.P_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Gepflanzt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Gepflanzt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Bluet_Von)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Bluet_Von)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Bluet_Bis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Bluet_Bis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Notiz)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Notiz)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Kauf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kauf.K_Shop)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Schaedling)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Schaedling.S_Bez)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Standort)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Standort.SO_Bez)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Steckbrief)
        </dt>
        @**@
        <dd>
            @Html.DisplayFor(model => model.Steckbrief.ST_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Topf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Topf.T_Bez)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_U_Besitzer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.U_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Löschen" class="btn btn-default" /> |
            @Html.ActionLink("Zurück zur Liste", "Index")
        </div>
    }
</div>

CommunityPlantsWebAppASpMVC/CommunityPlantsWebAppASpMVC/Views/Pflanzens/Details.cshtml
@model GemeinschaftsBalkonWebApp01.Models.Pflanzen

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pflanzen</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.P_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Gepflanzt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Gepflanzt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Bluet_Von)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Bluet_Von)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Bluet_Bis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Bluet_Bis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Notiz)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Notiz)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Kauf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kauf.K_Shop)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Schaedling)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Schaedling.S_Bez)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Standort)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Standort.SO_Bez)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Topf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Topf.T_Bez)
        </dd>

        <!--Label anzeigendes DisplaynameView   hier von User.U_Name > P_U_Besitzer -->
        <dt>
            @Html.DisplayNameFor(model => model.P_U_Besitzer)
        </dt>

        <!--Daten anzeigendes DisplaynameView-->
        <dd>
            @Html.DisplayFor(model => model.User.U_Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.P_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CommunityPlantsWebAppASpMVC/CommunityPlantsWebAppASpMVC/Views/Pflanzens/Index.cshtml
@model IEnumerable<GemeinschaftsBalkonWebApp01.Models.Pflanzen>

@{
    ViewBag.Title = "Index";
}

<h2>Übersicht</h2>              @*h2>Index @ViewBag.suchlehreranzeige</h2>*@
<h4>Pflanzen</h4>
<br />
<p>
    @Html.ActionLink("Create New ?", "Create")
</p>

<br />

@using (Html.BeginForm())
{
<div class="form-group">
    Suche nach User:

    @Html.DropDownList("suchuser", null, "Alle User", htmlAttributes: new { @class = "form-control" })

</div>
<div class="form-group">
    <input type="submit" value="Suche" class="btn btn-default" />
</div>
}
<br />

@Html.Partial("_pflanzens", Model)








@* alles von hier landet im partiellen view und wird gelöscht!

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.P_Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.P_Gepflanzt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.P_Bluet_Von)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.P_Bluet_Bis)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.P_Notiz)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Kauf.K_Shop)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Schaedling.S_Bez)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Standort.SO_Bez)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Steckbrief.ST_Name)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Topf.T_Bez)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.User.U_Name)
                </th>
                <th></th>
        </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.P_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.P_Gepflanzt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.P_Bluet_Von)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.P_Bluet_Bis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.P_Notiz)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kauf.K_Shop)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Schaedling.S_Bez)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Standort.SO_Bez)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Steckbrief.ST_Name)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Topf.T_Bez)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.U_Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.P_ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.P_ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.P_ID })

                @*
                    @Html.ActionLink("Edit", "Edit", new { /* id = item.PrimatyKey */ }) |
                    @Html.ActionLink("Details", "Details", new { id = item.PrimatyKey }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.PrimatyKey })

                    hätte man 2 PKs:
                    @Html.ActionLink("Edit", "Edit", new { /* klasse = item.ST_K_Klasse, stunden = item.ST_Stunde */ }) |
                    --||--
                    --||--
                        statt item > Model in Deteils.cshtml zu sehen zB eine einzelne StundenInstanz
                *
            </td>
        </tr>
    }
    </table>
*@

CommunityPlantsWebAppASpMVC/CommunityPlantsWebAppASpMVC/Views/Pflanzens/_pflanzens.cshtml
@model IEnumerable<GemeinschaftsBalkonWebApp01.Models.Pflanzen>


        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.P_Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.P_Gepflanzt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.P_Bluet_Von)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.P_Bluet_Bis)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.P_Notiz)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Kauf.K_Shop)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Schaedling.S_Bez)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Standort.SO_Bez)
                </th>
                @*
                <th>
                    @Html.DisplayNameFor(model => model.Steckbrief.ST_Name)
                </th>
                *@
                <th>
                    @Html.DisplayNameFor(model => model.Topf.T_Bez)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.User.U_Name)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.P_Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.P_Gepflanzt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.P_Bluet_Von)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.P_Bluet_Bis)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.P_Notiz)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kauf.K_Shop)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Schaedling.S_Bez)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Standort.SO_Bez)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Topf.T_Bez)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.U_Name)
                    </td>
                    <td>
                        @if (ViewBag.Linksnichtzeigen == null)
                        {
                            @Html.ActionLink("Edit", "Edit", new { id = item.P_ID }) @Html.Raw(" | ")
                            @Html.ActionLink("Details", "Details", new { id = item.P_ID }) @Html.Raw(" | ")
                            @Html.ActionLink("Delete", "Delete", new { id = item.P_ID })
                        }
                        else
                        {
                            @Html.ActionLink("Details", "Details", "Pflanzens", new { id = item.P_ID }, null)
                        }

                    </td>
                </tr>
            }

        </table>